/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  _: {
    Introduction: ['intro/overview'],
    'Quick Start': ['quickstart/setup', 'quickstart/sdk'],
    'Credential': ['credential/access-token', 'credential/signature-algorithm'],
    'Transaction API': [
      'transaction-api/overview',
      {
        type: 'category',
        label: 'Payment API',
        items: [
          'transaction-api/payment/create-payment-url',
          'transaction-api/payment/check-payment-status',
          'transaction-api/payment/callback-query',
        ],
      },
      {
        type: 'category',
        label: 'Payout API',
        items: [
          'transaction-api/payout/create-payout-request',
          'transaction-api/payout/check-payout-status',
          'transaction-api/payout/callback-query',
        ],
      },
    ],
    Appendix: [
      'appendix/error-code',
      'appendix/payment-method',
    ],
  },
};

module.exports = sidebars;
